name: GitHub Pages deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-20.04
      steps:
        - name: 📚 Checkout
          uses: actions/checkout@v2
        - name: 🟢 Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: 16
            registry-url: "https://registry.npmjs.org"
        - name: Build Storybook
          run: npm run build:storybook
        - name: Deploy to GitHub Pages
          uses: Cecilapp/GitHub-Pages-deploy@v3
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          with:
            build_dir: storybook-static

