name: "🚀 release"

on:
  release:
    types: [published]

jobs:
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          working-directory: ./
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm build
      - run: npm publish
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_AUTH_TOKEN}}
